// 中国主要城市经度数据库（覆盖直辖市/省会/地级市/部分区县）
// 用于真太阳时校正
// 数据来源：百度百科/高德公开数据

export interface CityRecord {
  name: string;
  province: string;
  longitude: number; // 东经为正
}

export const CITIES: CityRecord[] = [
  // 直辖市
  { name: '北京', province: '北京', longitude: 116.41 },
  { name: '上海', province: '上海', longitude: 121.47 },
  { name: '天津', province: '天津', longitude: 117.19 },
  { name: '重庆', province: '重庆', longitude: 106.55 },
  // 河北
  { name: '石家庄', province: '河北', longitude: 114.51 },
  { name: '唐山', province: '河北', longitude: 118.18 },
  { name: '秦皇岛', province: '河北', longitude: 119.59 },
  { name: '邯郸', province: '河北', longitude: 114.49 },
  { name: '邢台', province: '河北', longitude: 114.50 },
  { name: '保定', province: '河北', longitude: 115.48 },
  { name: '张家口', province: '河北', longitude: 114.88 },
  { name: '承德', province: '河北', longitude: 117.96 },
  { name: '沧州', province: '河北', longitude: 116.84 },
  { name: '廊坊', province: '河北', longitude: 116.68 },
  { name: '衡水', province: '河北', longitude: 115.67 },
  // 山西
  { name: '太原', province: '山西', longitude: 112.55 },
  { name: '大同', province: '山西', longitude: 113.30 },
  { name: '阳泉', province: '山西', longitude: 113.57 },
  { name: '长治', province: '山西', longitude: 113.04 },
  { name: '晋城', province: '山西', longitude: 112.83 },
  { name: '朔州', province: '山西', longitude: 112.43 },
  { name: '晋中', province: '山西', longitude: 112.75 },
  { name: '运城', province: '山西', longitude: 110.97 },
  { name: '忻州', province: '山西', longitude: 112.71 },
  { name: '临汾', province: '山西', longitude: 111.51 },
  { name: '吕梁', province: '山西', longitude: 111.13 },
  // 内蒙古
  { name: '呼和浩特', province: '内蒙古', longitude: 111.75 },
  { name: '包头', province: '内蒙古', longitude: 109.84 },
  { name: '乌海', province: '内蒙古', longitude: 106.79 },
  { name: '赤峰', province: '内蒙古', longitude: 118.89 },
  { name: '通辽', province: '内蒙古', longitude: 122.26 },
  { name: '鄂尔多斯', province: '内蒙古', longitude: 109.78 },
  { name: '呼伦贝尔', province: '内蒙古', longitude: 119.76 },
  { name: '巴彦淖尔', province: '内蒙古', longitude: 107.42 },
  { name: '乌兰察布', province: '内蒙古', longitude: 113.11 },
  // 辽宁
  { name: '沈阳', province: '辽宁', longitude: 123.43 },
  { name: '大连', province: '辽宁', longitude: 121.62 },
  { name: '鞍山', province: '辽宁', longitude: 122.99 },
  { name: '抚顺', province: '辽宁', longitude: 123.95 },
  { name: '本溪', province: '辽宁', longitude: 123.76 },
  { name: '丹东', province: '辽宁', longitude: 124.39 },
  { name: '锦州', province: '辽宁', longitude: 121.13 },
  { name: '营口', province: '辽宁', longitude: 122.23 },
  { name: '阜新', province: '辽宁', longitude: 121.66 },
  { name: '辽阳', province: '辽宁', longitude: 123.17 },
  { name: '盘锦', province: '辽宁', longitude: 122.07 },
  { name: '铁岭', province: '辽宁', longitude: 123.84 },
  { name: '朝阳', province: '辽宁', longitude: 120.45 },
  { name: '葫芦岛', province: '辽宁', longitude: 120.84 },
  // 吉林
  { name: '长春', province: '吉林', longitude: 125.33 },
  { name: '吉林市', province: '吉林', longitude: 126.55 },
  { name: '四平', province: '吉林', longitude: 124.35 },
  { name: '辽源', province: '吉林', longitude: 125.15 },
  { name: '通化', province: '吉林', longitude: 125.94 },
  { name: '白山', province: '吉林', longitude: 126.42 },
  { name: '松原', province: '吉林', longitude: 124.83 },
  { name: '白城', province: '吉林', longitude: 122.84 },
  { name: '延吉', province: '吉林', longitude: 129.51 },
  // 黑龙江
  { name: '哈尔滨', province: '黑龙江', longitude: 126.64 },
  { name: '齐齐哈尔', province: '黑龙江', longitude: 123.92 },
  { name: '鸡西', province: '黑龙江', longitude: 130.97 },
  { name: '鹤岗', province: '黑龙江', longitude: 130.28 },
  { name: '双鸭山', province: '黑龙江', longitude: 131.16 },
  { name: '大庆', province: '黑龙江', longitude: 125.00 },
  { name: '伊春', province: '黑龙江', longitude: 128.84 },
  { name: '佳木斯', province: '黑龙江', longitude: 130.32 },
  { name: '七台河', province: '黑龙江', longitude: 130.91 },
  { name: '牡丹江', province: '黑龙江', longitude: 129.63 },
  { name: '黑河', province: '黑龙江', longitude: 127.49 },
  { name: '绥化', province: '黑龙江', longitude: 126.97 },
  // 江苏
  { name: '南京', province: '江苏', longitude: 118.78 },
  { name: '无锡', province: '江苏', longitude: 120.30 },
  { name: '徐州', province: '江苏', longitude: 117.19 },
  { name: '常州', province: '江苏', longitude: 119.95 },
  { name: '苏州', province: '江苏', longitude: 120.62 },
  { name: '南通', province: '江苏', longitude: 120.86 },
  { name: '连云港', province: '江苏', longitude: 119.22 },
  { name: '淮安', province: '江苏', longitude: 119.02 },
  { name: '盐城', province: '江苏', longitude: 120.16 },
  { name: '扬州', province: '江苏', longitude: 119.41 },
  { name: '镇江', province: '江苏', longitude: 119.42 },
  { name: '泰州', province: '江苏', longitude: 119.93 },
  { name: '宿迁', province: '江苏', longitude: 118.28 },
  // 浙江
  { name: '杭州', province: '浙江', longitude: 120.16 },
  { name: '宁波', province: '浙江', longitude: 121.55 },
  { name: '温州', province: '浙江', longitude: 120.65 },
  { name: '嘉兴', province: '浙江', longitude: 120.76 },
  { name: '湖州', province: '浙江', longitude: 120.09 },
  { name: '绍兴', province: '浙江', longitude: 120.58 },
  { name: '金华', province: '浙江', longitude: 119.65 },
  { name: '衢州', province: '浙江', longitude: 118.87 },
  { name: '舟山', province: '浙江', longitude: 122.11 },
  { name: '台州', province: '浙江', longitude: 121.42 },
  { name: '丽水', province: '浙江', longitude: 119.92 },
  // 安徽
  { name: '合肥', province: '安徽', longitude: 117.27 },
  { name: '芜湖', province: '安徽', longitude: 118.38 },
  { name: '蚌埠', province: '安徽', longitude: 117.36 },
  { name: '淮南', province: '安徽', longitude: 117.01 },
  { name: '马鞍山', province: '安徽', longitude: 118.51 },
  { name: '淮北', province: '安徽', longitude: 116.80 },
  { name: '铜陵', province: '安徽', longitude: 117.81 },
  { name: '安庆', province: '安徽', longitude: 117.04 },
  { name: '黄山', province: '安徽', longitude: 118.32 },
  { name: '滁州', province: '安徽', longitude: 118.32 },
  { name: '阜阳', province: '安徽', longitude: 115.81 },
  { name: '宿州', province: '安徽', longitude: 116.97 },
  { name: '六安', province: '安徽', longitude: 116.51 },
  { name: '亳州', province: '安徽', longitude: 115.78 },
  { name: '池州', province: '安徽', longitude: 117.49 },
  { name: '宣城', province: '安徽', longitude: 118.76 },
  // 福建
  { name: '福州', province: '福建', longitude: 119.30 },
  { name: '厦门', province: '福建', longitude: 118.09 },
  { name: '莆田', province: '福建', longitude: 119.01 },
  { name: '三明', province: '福建', longitude: 117.64 },
  { name: '泉州', province: '福建', longitude: 118.68 },
  { name: '漳州', province: '福建', longitude: 117.65 },
  { name: '南平', province: '福建', longitude: 118.18 },
  { name: '龙岩', province: '福建', longitude: 117.03 },
  { name: '宁德', province: '福建', longitude: 119.52 },
  // 江西
  { name: '南昌', province: '江西', longitude: 115.86 },
  { name: '景德镇', province: '江西', longitude: 117.21 },
  { name: '萍乡', province: '江西', longitude: 113.85 },
  { name: '九江', province: '江西', longitude: 115.99 },
  { name: '新余', province: '江西', longitude: 114.92 },
  { name: '鹰潭', province: '江西', longitude: 117.07 },
  { name: '赣州', province: '江西', longitude: 114.94 },
  { name: '吉安', province: '江西', longitude: 114.99 },
  { name: '宜春', province: '江西', longitude: 114.38 },
  { name: '抚州', province: '江西', longitude: 116.36 },
  { name: '上饶', province: '江西', longitude: 117.96 },
  // 山东
  { name: '济南', province: '山东', longitude: 117.00 },
  { name: '青岛', province: '山东', longitude: 120.38 },
  { name: '淄博', province: '山东', longitude: 118.05 },
  { name: '枣庄', province: '山东', longitude: 117.32 },
  { name: '东营', province: '山东', longitude: 118.67 },
  { name: '烟台', province: '山东', longitude: 121.40 },
  { name: '潍坊', province: '山东', longitude: 119.16 },
  { name: '济宁', province: '山东', longitude: 116.59 },
  { name: '泰安', province: '山东', longitude: 117.09 },
  { name: '威海', province: '山东', longitude: 122.12 },
  { name: '日照', province: '山东', longitude: 119.53 },
  { name: '临沂', province: '山东', longitude: 118.36 },
  { name: '德州', province: '山东', longitude: 116.36 },
  { name: '聊城', province: '山东', longitude: 115.99 },
  { name: '滨州', province: '山东', longitude: 117.97 },
  { name: '菏泽', province: '山东', longitude: 115.44 },
  // 河南
  { name: '郑州', province: '河南', longitude: 113.62 },
  { name: '开封', province: '河南', longitude: 114.30 },
  { name: '洛阳', province: '河南', longitude: 112.45 },
  { name: '平顶山', province: '河南', longitude: 113.20 },
  { name: '安阳', province: '河南', longitude: 114.39 },
  { name: '鹤壁', province: '河南', longitude: 114.30 },
  { name: '新乡', province: '河南', longitude: 113.93 },
  { name: '焦作', province: '河南', longitude: 113.25 },
  { name: '濮阳', province: '河南', longitude: 115.04 },
  { name: '许昌', province: '河南', longitude: 113.85 },
  { name: '漯河', province: '河南', longitude: 114.02 },
  { name: '三门峡', province: '河南', longitude: 111.20 },
  { name: '南阳', province: '河南', longitude: 112.53 },
  { name: '商丘', province: '河南', longitude: 115.65 },
  { name: '信阳', province: '河南', longitude: 114.07 },
  { name: '周口', province: '河南', longitude: 114.65 },
  { name: '驻马店', province: '河南', longitude: 114.02 },
  // 湖北
  { name: '武汉', province: '湖北', longitude: 114.31 },
  { name: '黄石', province: '湖北', longitude: 115.05 },
  { name: '十堰', province: '湖北', longitude: 110.80 },
  { name: '宜昌', province: '湖北', longitude: 111.29 },
  { name: '襄阳', province: '湖北', longitude: 112.13 },
  { name: '鄂州', province: '湖北', longitude: 114.88 },
  { name: '荆门', province: '湖北', longitude: 112.20 },
  { name: '孝感', province: '湖北', longitude: 113.92 },
  { name: '荆州', province: '湖北', longitude: 112.24 },
  { name: '黄冈', province: '湖北', longitude: 114.87 },
  { name: '咸宁', province: '湖北', longitude: 114.32 },
  { name: '随州', province: '湖北', longitude: 113.37 },
  { name: '恩施', province: '湖北', longitude: 109.49 },
  // 湖南
  { name: '长沙', province: '湖南', longitude: 112.94 },
  { name: '株洲', province: '湖南', longitude: 113.13 },
  { name: '湘潭', province: '湖南', longitude: 112.92 },
  { name: '衡阳', province: '湖南', longitude: 112.57 },
  { name: '邵阳', province: '湖南', longitude: 111.47 },
  { name: '岳阳', province: '湖南', longitude: 113.13 },
  { name: '常德', province: '湖南', longitude: 111.68 },
  { name: '张家界', province: '湖南', longitude: 110.48 },
  { name: '益阳', province: '湖南', longitude: 112.33 },
  { name: '郴州', province: '湖南', longitude: 113.02 },
  { name: '永州', province: '湖南', longitude: 111.61 },
  { name: '怀化', province: '湖南', longitude: 109.97 },
  { name: '娄底', province: '湖南', longitude: 111.99 },
  // 广东
  { name: '广州', province: '广东', longitude: 113.27 },
  { name: '韶关', province: '广东', longitude: 113.60 },
  { name: '深圳', province: '广东', longitude: 114.06 },
  { name: '珠海', province: '广东', longitude: 113.58 },
  { name: '汕头', province: '广东', longitude: 116.68 },
  { name: '佛山', province: '广东', longitude: 113.12 },
  { name: '江门', province: '广东', longitude: 113.08 },
  { name: '湛江', province: '广东', longitude: 110.36 },
  { name: '茂名', province: '广东', longitude: 110.92 },
  { name: '肇庆', province: '广东', longitude: 112.47 },
  { name: '惠州', province: '广东', longitude: 114.41 },
  { name: '梅州', province: '广东', longitude: 116.13 },
  { name: '汕尾', province: '广东', longitude: 115.38 },
  { name: '河源', province: '广东', longitude: 114.70 },
  { name: '阳江', province: '广东', longitude: 111.98 },
  { name: '清远', province: '广东', longitude: 113.04 },
  { name: '东莞', province: '广东', longitude: 113.75 },
  { name: '中山', province: '广东', longitude: 113.39 },
  { name: '潮州', province: '广东', longitude: 116.62 },
  { name: '揭阳', province: '广东', longitude: 116.37 },
  { name: '云浮', province: '广东', longitude: 112.04 },
  // 广西
  { name: '南宁', province: '广西', longitude: 108.37 },
  { name: '柳州', province: '广西', longitude: 109.42 },
  { name: '桂林', province: '广西', longitude: 110.29 },
  { name: '梧州', province: '广西', longitude: 111.27 },
  { name: '北海', province: '广西', longitude: 109.12 },
  { name: '防城港', province: '广西', longitude: 108.35 },
  { name: '钦州', province: '广西', longitude: 108.65 },
  { name: '贵港', province: '广西', longitude: 109.60 },
  { name: '玉林', province: '广西', longitude: 110.16 },
  { name: '百色', province: '广西', longitude: 106.61 },
  { name: '贺州', province: '广西', longitude: 111.55 },
  { name: '河池', province: '广西', longitude: 108.06 },
  { name: '来宾', province: '广西', longitude: 109.23 },
  { name: '崇左', province: '广西', longitude: 107.36 },
  // 海南
  { name: '海口', province: '海南', longitude: 110.32 },
  { name: '三亚', province: '海南', longitude: 109.51 },
  { name: '三沙', province: '海南', longitude: 112.33 },
  { name: '儋州', province: '海南', longitude: 109.57 },
  // 四川
  { name: '成都', province: '四川', longitude: 104.07 },
  { name: '自贡', province: '四川', longitude: 104.78 },
  { name: '攀枝花', province: '四川', longitude: 101.72 },
  { name: '泸州', province: '四川', longitude: 105.44 },
  { name: '德阳', province: '四川', longitude: 104.39 },
  { name: '绵阳', province: '四川', longitude: 104.73 },
  { name: '广元', province: '四川', longitude: 105.84 },
  { name: '遂宁', province: '四川', longitude: 105.57 },
  { name: '内江', province: '四川', longitude: 105.06 },
  { name: '乐山', province: '四川', longitude: 103.77 },
  { name: '南充', province: '四川', longitude: 106.11 },
  { name: '眉山', province: '四川', longitude: 103.85 },
  { name: '宜宾', province: '四川', longitude: 104.62 },
  { name: '广安', province: '四川', longitude: 106.63 },
  { name: '达州', province: '四川', longitude: 107.47 },
  { name: '雅安', province: '四川', longitude: 103.00 },
  { name: '巴中', province: '四川', longitude: 106.76 },
  { name: '资阳', province: '四川', longitude: 104.65 },
  // 贵州
  { name: '贵阳', province: '贵州', longitude: 106.71 },
  { name: '六盘水', province: '贵州', longitude: 104.83 },
  { name: '遵义', province: '贵州', longitude: 106.91 },
  { name: '安顺', province: '贵州', longitude: 105.95 },
  { name: '铜仁', province: '贵州', longitude: 109.19 },
  { name: '毕节', province: '贵州', longitude: 105.29 },
  { name: '兴义', province: '贵州', longitude: 104.90 },
  // 云南
  { name: '昆明', province: '云南', longitude: 102.71 },
  { name: '曲靖', province: '云南', longitude: 103.80 },
  { name: '玉溪', province: '云南', longitude: 102.55 },
  { name: '保山', province: '云南', longitude: 99.16 },
  { name: '昭通', province: '云南', longitude: 103.72 },
  { name: '丽江', province: '云南', longitude: 100.23 },
  { name: '普洱', province: '云南', longitude: 100.97 },
  { name: '临沧', province: '云南', longitude: 100.08 },
  { name: '楚雄', province: '云南', longitude: 101.55 },
  { name: '大理', province: '云南', longitude: 100.23 },
  // 西藏
  { name: '拉萨', province: '西藏', longitude: 91.13 },
  { name: '日喀则', province: '西藏', longitude: 88.88 },
  { name: '昌都', province: '西藏', longitude: 97.18 },
  { name: '林芝', province: '西藏', longitude: 94.36 },
  { name: '山南', province: '西藏', longitude: 91.77 },
  { name: '那曲', province: '西藏', longitude: 92.05 },
  // 陕西
  { name: '西安', province: '陕西', longitude: 108.94 },
  { name: '铜川', province: '陕西', longitude: 108.95 },
  { name: '宝鸡', province: '陕西', longitude: 107.24 },
  { name: '咸阳', province: '陕西', longitude: 108.71 },
  { name: '渭南', province: '陕西', longitude: 109.51 },
  { name: '延安', province: '陕西', longitude: 109.49 },
  { name: '汉中', province: '陕西', longitude: 107.02 },
  { name: '榆林', province: '陕西', longitude: 109.73 },
  { name: '安康', province: '陕西', longitude: 109.03 },
  { name: '商洛', province: '陕西', longitude: 109.94 },
  // 甘肃
  { name: '兰州', province: '甘肃', longitude: 103.83 },
  { name: '嘉峪关', province: '甘肃', longitude: 98.29 },
  { name: '金昌', province: '甘肃', longitude: 102.19 },
  { name: '白银', province: '甘肃', longitude: 104.14 },
  { name: '天水', province: '甘肃', longitude: 105.72 },
  { name: '武威', province: '甘肃', longitude: 102.64 },
  { name: '张掖', province: '甘肃', longitude: 100.45 },
  { name: '平凉', province: '甘肃', longitude: 106.66 },
  { name: '酒泉', province: '甘肃', longitude: 98.50 },
  { name: '庆阳', province: '甘肃', longitude: 107.64 },
  { name: '定西', province: '甘肃', longitude: 104.62 },
  { name: '陇南', province: '甘肃', longitude: 104.92 },
  // 青海
  { name: '西宁', province: '青海', longitude: 101.78 },
  { name: '海东', province: '青海', longitude: 102.10 },
  { name: '格尔木', province: '青海', longitude: 94.91 },
  // 宁夏
  { name: '银川', province: '宁夏', longitude: 106.27 },
  { name: '石嘴山', province: '宁夏', longitude: 106.38 },
  { name: '吴忠', province: '宁夏', longitude: 106.20 },
  { name: '固原', province: '宁夏', longitude: 106.24 },
  { name: '中卫', province: '宁夏', longitude: 105.19 },
  // 新疆
  { name: '乌鲁木齐', province: '新疆', longitude: 87.62 },
  { name: '克拉玛依', province: '新疆', longitude: 84.89 },
  { name: '吐鲁番', province: '新疆', longitude: 89.18 },
  { name: '哈密', province: '新疆', longitude: 93.51 },
  { name: '阿克苏', province: '新疆', longitude: 80.26 },
  { name: '喀什', province: '新疆', longitude: 75.99 },
  { name: '和田', province: '新疆', longitude: 79.92 },
  { name: '伊宁', province: '新疆', longitude: 81.32 },
  { name: '塔城', province: '新疆', longitude: 82.99 },
  { name: '阿勒泰', province: '新疆', longitude: 88.14 },
  // 港澳台
  { name: '香港', province: '香港', longitude: 114.17 },
  { name: '澳门', province: '澳门', longitude: 113.55 },
  { name: '台北', province: '台湾', longitude: 121.56 },
  { name: '高雄', province: '台湾', longitude: 120.30 },
  { name: '台中', province: '台湾', longitude: 120.67 },
];

// 按拼音首字母分组（简化版：按首字分）
export function searchCities(keyword: string): CityRecord[] {
  if (!keyword.trim()) return CITIES.slice(0, 30);
  const k = keyword.toLowerCase();
  return CITIES.filter(c =>
    c.name.includes(k) ||
    c.province.includes(k)
  ).slice(0, 50);
}
