import { Solar } from 'lunar-javascript';
const s = Solar.fromYmdHms(1990, 5, 20, 9, 30, 0);
const l = s.getLunar();
const bz = l.getEightChar();
console.log('八字类:', Object.keys(bz));
console.log('年柱:', bz.getYear());
console.log('月柱:', bz.getMonth());
console.log('日柱:', bz.getDay());
console.log('时柱:', bz.getTime());
console.log('年干:', bz.getYearGan());
console.log('年支:', bz.getYearZhi());
console.log('日主:', bz.getDayGan());
console.log('---十神---');
console.log('年干十神:', bz.getYearShiShenGan());
console.log('月干十神:', bz.getMonthShiShenGan());
console.log('时干十神:', bz.getTimeShiShenGan());
console.log('---藏干---');
console.log('年支藏干:', bz.getYearHideGan());
console.log('月支藏干:', bz.getMonthHideGan());
console.log('---纳音---');
console.log('年纳音:', bz.getYearNaYin());
console.log('日纳音:', bz.getDayNaYin());
console.log('---大运---');
const yun = bz.getYun(1); // 1=男
console.log('大运对象keys:', Object.keys(yun));
console.log('起运岁数:', yun.getStartYear());
console.log('起运年龄:', yun.getStartAge());
console.log('顺逆:', yun.getDirection());
console.log('---大运列表---');
const dylist = yun.getDaYun();
console.log('大运数:', dylist.length);
dylist.slice(0, 4).forEach(dy => {
  console.log('  ' + dy.getStartAge() + '岁起: ' + dy.getGanZhi() + ' (' + dy.getStartYear() + '年)');
});
console.log('---流年---');
console.log('2025流年:', yun.getLiuNian(2025)?.getGanZhi?.());
console.log('---神煞---');
console.log('年神煞:', bz.getYearShenSha());
console.log('日神煞:', bz.getDayShenSha());
